### ISSUE TITLE
stm32f0 GPIO structures

### ISSUE THREAD

**Issue by HarkonenBade** [stm32-rs/stm32-rs#115]
Is it expected for the device modules such as `stm32f0::stm32f0x2` to contain structures for `GPIO{A..F}` but only modules with `RegisterBlock` definitions for `gpioa gpiof`? As `GPIOA` references `gpioa::RegisterBlock`, but the rest all reference `gpiof::RegisterBlock`. Is there a reason that there are not modules being generated for gpio{b..e}?

**Comment by adamgreig** [comment]
This is essentially an svd2rust question. GPIOB..E are all `derivedFrom="GPIOF"`; GPIOA is different because it has a non-zero reset value for some pins due to JTAG default functionality. Consequently svd2rust generates `gpioa::RegisterBlock` with the JTAG default behaviour, and `gpiof::RegisterBlock` which all the others use. This is nicer than generating a `RegisterBlock` for every one since it would be a huge amount of duplicate code and the types are identical.

I'd rather see it generate `gpio::RegisterBlock` and abstract reset values to per-peripheral constants (which is what I did [in](https://github.com/adamgreig/stm32ral/blob/master/src/stm32f0/peripherals/gpio.rs#L2552) [stm32ral](https://github.com/adamgreig/stm32ral/blob/master/src/stm32f0/instances/gpio.rs#L15)), but it doesn't.

**Comment by HarkonenBade** [comment]
Ok, that is fair. I would be interested in a way to work out which `RegisterBlock` type each GPIO structure uses. A possible thought would be making the `ptr` function be from a trait that names the `RegisterBlock` type as an associated type. Or alternatively i'd be interested in seeing the other modules implemented with just a stub `type RegisterBlock = gpioa::RegisterBlock;` As my current issue is finding a way to reliably name the RegisterBlock type for a given GPIO block as part of a macro definition of GPIO traits in a hal crate.

**Comment by adamgreig** [comment]
Worth opening an issue on [the svd2rust tracker](https://github.com/rust-embedded/svd2rust/issues) to discuss.
