### ISSUE TITLE
stm32h7 ethernet naming

### ISSUE THREAD

**Issue by jordens** [stm32-rs/stm32-rs#191]
(Except for some registers in `Ethernet_MAC` and the registers in `Ethernet_MMC`):

The STM32H7 ethernet peripherals and registers are currently names as `Ethernet_$X.$X$Y` (where e.g. `$X=DMA` and `$Y=DSR`). The ref manual typically names them `ETH_$X$Y`.

 @ehntoo Does it make sense to remove the `$X.$X` duplication and name that stuff `ETH_$X.$Y` (stripping the `$X` from the register name) or `ETH.$X$Y` (merging the ethernet peripherals)?

**Comment by ehntoo** [comment]
Due to some career changes I haven't had any real opportunity to actually sit down and use the H7 Ethernet peripheral. As I recall, there was quite some variability in the way the reference manual referred to things. If there's a clean way to unify things, especially one that would stay consistent with other parts, I think it could well be worth pursuing. That said, I wouldn't place too much weight on my opinions here anyway, I've just been fiddling with embedded rust at odd hours in evenings and on weekends..

**Comment by jordens** [comment]
The newer SVD has the MMC merged into the MAC and the MTL starts at `0x40028c00`.
