### ISSUE TITLE
stm32wb: svd for TIM2->CNT is.... wonky

### ISSUE THREAD

**Issue by karlp** [stm32-rs/stm32-rs#626]
CNT is _either_ a 32bit register, _or_ 31bits plus a single flag for UIFCPY.

The current SVD produces the flag bit, and then "cnt_h (15bit)" and "cnt_l (16bit)" which is... unhelpful.

Can we make overlapping definitions? Can I make CNT just be 32bit and _also_ define UIFCPY at bit 31?

**Comment by adamgreig** [comment]
It's totally fine to make overlapping definitions; svd2rust will do the right thing and generate a method for each field. A similar problem is fixed in the F7 devices [here](https://github.com/stm32-rs/stm32-rs/blob/master/devices/common_patches/f7_tim.yaml#L21-L31) for example.

In this case it's probably best to delete `cnt_h`, modify `cnt_l` to be named `cnt` and make it 32 bits wide (or keep it as 16 on the other timers).

**Comment by karlp** [comment]
FYI: I've shelved all my rust work, so I won't be working on any more patches myself, I'm afraid.
